In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import Input
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt 
import numpy as np

In [4]:
safety_df = pd.read_csv('Safety_DataSet_Aggregated.csv')
safety_df

      bookingID  Accuracy     Bearing  ...  second     Speed  label
0             0      12.0  143.298294  ...     0.0  3.442991    0.0
1             0       8.0  143.298294  ...     1.0  0.228454    0.0
2             0       8.0  143.298294  ...     2.0  0.228454    0.0
3             0       8.0  143.298294  ...     3.0  0.228454    0.0
4             0       8.0  143.298294  ...     4.0  0.228454    0.0
...         ...       ...         ...  ...     ...       ...    ...
9074         14      16.0  131.642502  ...   443.0  2.029639    0.0
9075         14      16.0  131.642502  ...   444.0  1.567298    0.0
9076         14      16.0  131.642502  ...   445.0  1.567298    0.0
9077         14      16.0  131.642502  ...   446.0  1.567298    0.0
9078         14      16.0  131.642502  ...     NaN       NaN    NaN

[9079 rows x 12 columns]

In [5]:
safety_df['label'].value_counts()

0.0    5710
1.0    3368
Name: label, dtype: int64

In [6]:
balanced_label0_df = safety_df[safety_df['label'] == 0].sample(n=len(safety_df[safety_df['label'] == 1]))
balanced_label0_df

      bookingID  Accuracy     Bearing  ...  second      Speed  label
8244         13     3.900  247.000000  ...  1034.0  18.976583    0.0
197           0    16.000  168.032196  ...   197.0   2.375495    0.0
5482          8     5.083  317.000000  ...   370.0   0.930000    0.0
616           0    12.000  279.923950  ...  1202.0  12.102637    0.0
7196         13     8.000   11.000000  ...   510.0  11.404697    0.0
...         ...       ...         ...  ...     ...        ...    ...
174           0    16.000  142.124496  ...   174.0   0.227891    0.0
3511          6     6.000  117.000000  ...   367.0   4.147976    0.0
6222         13     6.000  108.000000  ...    23.0   6.645902    0.0
4612          7     3.375   26.000000  ...   379.0   2.382649    0.0
5387          8     3.376    0.000000  ...   274.0   0.000000    0.0

[3368 rows x 12 columns]

In [7]:
balanced_label1_df = safety_df[safety_df['label']==1]
balanced_label1_df

      bookingID  Accuracy  Bearing  ...  second      Speed  label
1004          1       4.0    252.0  ...     0.0   4.756427    1.0
1005          1       4.0    236.0  ...     1.0   4.937211    1.0
1006          1       4.0    228.0  ...     2.0   5.544210    1.0
1007          1       4.0    222.0  ...     3.0   6.564030    1.0
1008          1       4.0    216.0  ...     4.0   7.358976    1.0
...         ...       ...      ...  ...     ...        ...    ...
8621         13       4.0    225.0  ...  1375.0  21.051840    1.0
8623         13       3.9    225.0  ...  1376.0  21.100790    1.0
8625         13       3.9    225.0  ...  1377.0  21.131630    1.0
8627         13       3.9    225.0  ...  1378.0  21.182209    1.0
8629         13       3.9    225.0  ...  1379.0  21.102415    1.0

[3368 rows x 12 columns]

In [8]:
final_df = pd.concat([balanced_label0_df,balanced_label1_df])
final_df = final_df.reset_index(drop=True)
final_df

      bookingID  Accuracy     Bearing  ...  second      Speed  label
0            13     3.900  247.000000  ...  1034.0  18.976583    0.0
1             0    16.000  168.032196  ...   197.0   2.375495    0.0
2             8     5.083  317.000000  ...   370.0   0.930000    0.0
3             0    12.000  279.923950  ...  1202.0  12.102637    0.0
4            13     8.000   11.000000  ...   510.0  11.404697    0.0
...         ...       ...         ...  ...     ...        ...    ...
6731         13     4.000  225.000000  ...  1375.0  21.051840    1.0
6732         13     3.900  225.000000  ...  1376.0  21.100790    1.0
6733         13     3.900  225.000000  ...  1377.0  21.131630    1.0
6734         13     3.900  225.000000  ...  1378.0  21.182209    1.0
6735         13     3.900  225.000000  ...  1379.0  21.102415    1.0

[6736 rows x 12 columns]

In [9]:
final_df['accelerometer_data'] = np.sqrt( (final_df['acceleration_x']) **2 + (final_df['acceleration_y']) **2 + (final_df['acceleration_z']) **2)
final_df

      bookingID  Accuracy     Bearing  ...      Speed  label  accelerometer_data
0            13     3.900  247.000000  ...  18.976583    0.0           10.142170
1             0    16.000  168.032196  ...   2.375495    0.0            9.850793
2             8     5.083  317.000000  ...   0.930000    0.0            9.014360
3             0    12.000  279.923950  ...  12.102637    0.0            9.749574
4            13     8.000   11.000000  ...  11.404697    0.0           12.501029
...         ...       ...         ...  ...        ...    ...                 ...
6731         13     4.000  225.000000  ...  21.051840    1.0           11.471598
6732         13     3.900  225.000000  ...  21.100790    1.0           10.133168
6733         13     3.900  225.000000  ...  21.131630    1.0            9.813597
6734         13     3.900  225.000000  ...  21.182209    1.0            8.831003
6735         13     3.900  225.000000  ...  21.102415    1.0           10.742601

[6736 rows x 13 columns]

In [10]:
features = list(final_df.columns.values)
features.remove('label')
features.remove('bookingID')
features.remove('acceleration_x')
features.remove('acceleration_y')
features.remove('acceleration_z')

In [11]:
y = final_df['label']
y

0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ...
6731    1.0
6732    1.0
6733    1.0
6734    1.0
6735    1.0
Name: label, Length: 6736, dtype: float64

In [12]:
from sklearn.decomposition import PCA
pca_gyro = PCA().fit(final_df.loc[:, ['gyro_x', 'gyro_y', 'gyro_z']])
pca_gyro.explained_variance_ratio_

array([0.62068321, 0.21719759, 0.1621192 ])

In [13]:
features.remove('gyro_z')
X = final_df[features]
X

      Accuracy     Bearing    gyro_x  ...  second      Speed  accelerometer_data
0        3.900  247.000000 -0.029092  ...  1034.0  18.976583           10.142170
1       16.000  168.032196 -0.002189  ...   197.0   2.375495            9.850793
2        5.083  317.000000  0.090408  ...   370.0   0.930000            9.014360
3       12.000  279.923950  0.047689  ...  1202.0  12.102637            9.749574
4        8.000   11.000000  0.026496  ...   510.0  11.404697           12.501029
...        ...         ...       ...  ...     ...        ...                 ...
6731     4.000  225.000000 -0.025427  ...  1375.0  21.051840           11.471598
6732     3.900  225.000000  0.045433  ...  1376.0  21.100790           10.133168
6733     3.900  225.000000  0.007559  ...  1377.0  21.131630            9.813597
6734     3.900  225.000000 -0.006490  ...  1378.0  21.182209            8.831003
6735     3.900  225.000000 -0.019929  ...  1379.0  21.102415           10.742601

[6736 rows x 7 columns]

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [15]:
X_train

      Accuracy     Bearing    gyro_x  ...  second      Speed  accelerometer_data
2316     8.000  340.410461  0.060836  ...  1384.0  17.247543            9.538134
2364     8.000   14.814796 -0.121157  ...  1504.0  18.945402            9.227633
944     16.000  135.702347  0.118085  ...   407.0   0.095500            9.937384
6529     6.000  265.000000 -0.021151  ...  1021.0  20.630278            9.306799
5584     5.970   31.000000 -0.015653  ...    76.0   2.296093            9.289774
...        ...         ...       ...  ...     ...        ...                 ...
3772     5.000  129.000000 -0.001257  ...   586.0  12.446338            9.879902
5191    10.000  102.151466 -0.137919  ...   778.0  14.840000            8.407967
5226    10.000  103.085045 -0.028736  ...   813.0   4.230000            9.605929
5390    10.000  129.627426  0.037074  ...   977.0   5.300000            9.971601
860      7.289   22.000000  0.028669  ...   189.0   0.000000           10.103373

[4715 rows x 7 columns]

In [16]:
X_test

      Accuracy     Bearing    gyro_x  ...  second      Speed  accelerometer_data
381      8.000  220.000000 -0.011377  ...   549.0   8.725396            9.566267
2877     4.764  219.000000  0.047606  ...   621.0   3.795704            9.875177
5314    10.000  102.130928 -0.010498  ...   901.0   4.630000           10.079847
2018     8.000  213.000000  0.004235  ...   327.0   7.680545            9.761917
2185    16.000  314.977234  0.091460  ...   103.0   2.345587            9.935965
...        ...         ...       ...  ...     ...        ...                 ...
2638    16.000  144.125198  0.070751  ...   121.0  12.213867           10.711998
3238     4.000  268.000000 -0.019929  ...   996.0  21.833536            9.539224
1561     3.000   35.000000  0.025884  ...   106.0   0.416914            9.673921
2759     8.000  264.167053 -0.093631  ...  1210.0   8.700075           10.327562
6073     4.000  215.000000 -0.002214  ...   565.0  15.942485           10.212391

[2021 rows x 7 columns]

In [17]:
y_train

2316    0.0
2364    0.0
944     0.0
6529    1.0
5584    1.0
       ...
3772    1.0
5191    1.0
5226    1.0
5390    1.0
860     0.0
Name: label, Length: 4715, dtype: float64

In [18]:
y_test

381     0.0
2877    0.0
5314    1.0
2018    0.0
2185    0.0
       ...
2638    0.0
3238    0.0
1561    0.0
2759    0.0
6073    1.0
Name: label, Length: 2021, dtype: float64

In [19]:
# Standard Scaler
ss = StandardScaler()
X_train_standardised = ss.fit_transform(X_train)
X_test_standardised = ss.transform(X_test)

In [20]:
X_train_standardised

array([[-0.01668714,  1.66912133,  1.15265738, ...,  2.17934873,
         0.91262184, -0.44225337],
       [-0.01668714, -1.51843203, -2.10584342, ...,  2.49421348,
         1.11372322, -0.87982021],
       [ 0.18272009, -0.33495339,  2.17768866, ..., -0.38417505,
        -1.11893682,  0.12038257],
       ...,
       [ 0.03316467, -0.65427395, -0.45108037, ...,  0.68111733,
        -0.62922957, -0.34671414],
       [ 0.03316467, -0.39442633,  0.72722235, ...,  1.11143248,
        -0.50249434,  0.16860201],
       [-0.03440946, -1.44808951,  0.57672962, ..., -0.95617934,
        -1.13024818,  0.35429879]])

In [21]:
X_test_standardised

array([[-0.01668714,  0.49031334, -0.14028554, ..., -0.01158511,
        -0.09677637, -0.40260734],
       [-0.09734737,  0.48052343,  0.91578524, ...,  0.17733374,
        -0.68066936,  0.03271797],
       [ 0.03316467, -0.66361467, -0.12454413, ...,  0.91201814,
        -0.58185191,  0.32114434],
       ...,
       [-0.14131666, -1.32082064,  0.52686658, ..., -1.17396079,
        -1.08086714, -0.25089828],
       [-0.01668714,  0.92270496, -1.61299929, ...,  1.72279485,
        -0.09977547,  0.67023204],
       [-0.11639076,  0.44136377,  0.02377363, ...,  0.03039686,
         0.75804536,  0.50792941]])

In [22]:
model = Sequential()
model.add(Dense(100, input_dim=X_train_standardised.shape[1], activation='relu'))
model.add(Dense(20, activation='relu'))
model.add(Dense(20, activation='relu'))
model.add(Dense(20, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [23]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 100)               800
_________________________________________________________________
dense_1 (Dense)              (None, 20)                2020
_________________________________________________________________
dense_2 (Dense)              (None, 20)                420
_________________________________________________________________
dense_3 (Dense)              (None, 20)                420
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 21
=================================================================
Total params: 3,681
Trainable params: 3,681
Non-trainable params: 0
_________________________________________________________________

In [24]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(X_train_standardised, y_train, epochs=20, batch_size=10)
test_loss, test_acc = model.evaluate(X_test, y_test)

Epoch 1/20
472/472 [==============================] - 1s 2ms/step - loss: 0.6255 - accuracy: 0.6698
Epoch 2/20
472/472 [==============================] - 1s 3ms/step - loss: 0.5432 - accuracy: 0.7404
Epoch 3/20
472/472 [==============================] - 1s 3ms/step - loss: 0.5073 - accuracy: 0.7555
Epoch 4/20
472/472 [==============================] - 1s 2ms/step - loss: 0.4858 - accuracy: 0.7614
Epoch 5/20
472/472 [==============================] - 1s 2ms/step - loss: 0.4697 - accuracy: 0.7733
Epoch 6/20
472/472 [==============================] - 1s 3ms/step - loss: 0.4525 - accuracy: 0.7828
Epoch 7/20
472/472 [==============================] - 1s 2ms/step - loss: 0.4482 - accuracy: 0.7792
Epoch 8/20
472/472 [==============================] - 1s 2ms/step - loss: 0.4369 - accuracy: 0.7915
Epoch 9/20
472/472 [==============================] - 1s 2ms/step - loss: 0.4232 - accuracy: 0.7869
Epoch 10/20
472/472 [==============================] - 1s 2ms/step - loss: 0.4208 - accuracy: 0.7938
Epoch 11/20
472/472 [==============================] - 1s 2ms/step - loss: 0.4154 - accuracy: 0.7966
Epoch 12/20
472/472 [==============================] - 1s 2ms/step - loss: 0.4142 - accuracy: 0.7955
Epoch 13/20
472/472 [==============================] - 1s 3ms/step - loss: 0.4028 - accuracy: 0.8004
Epoch 14/20
472/472 [==============================] - 1s 2ms/step - loss: 0.3974 - accuracy: 0.8068
Epoch 15/20
472/472 [==============================] - 1s 2ms/step - loss: 0.3933 - accuracy: 0.8051
Epoch 16/20
472/472 [==============================] - 1s 2ms/step - loss: 0.3872 - accuracy: 0.8091
Epoch 17/20
472/472 [==============================] - 1s 2ms/step - loss: 0.3806 - accuracy: 0.8170
Epoch 18/20
472/472 [==============================] - 1s 2ms/step - loss: 0.3795 - accuracy: 0.8153
Epoch 19/20
472/472 [==============================] - 1s 2ms/step - loss: 0.3750 - accuracy: 0.8146
Epoch 20/20
472/472 [==============================] - 1s 2ms/step - loss: 0.3685 - accuracy: 0.8189
64/64 [==============================] - 0s 2ms/step - loss: 206.0446 - accuracy: 0.5156

In [25]:
# Get actual predicted value 
print("CNN Error: %.2f%%" % (100-test_acc*100))

CNN Error: 48.44%